import{a as h,S as v,i as a}from"./assets/vendor-DcHCnVjq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();h.defaults.baseURL="https://pixabay.com/api/";const M="56000534-6fce5c682f9afcb7cf08332eb";async function f(r,e){const s={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await h.get("",{params:s})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more-btn"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(({webformatURL:s,largeImageURL:n,tags:t,likes:o,views:c,comments:P,downloads:S})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${s}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b>${o}</p>
            <p class="info-item"><b>Views</b>${c}</p>
            <p class="info-item"><b>Comments</b>${P}</p>
            <p class="info-item"><b>Downloads</b>${S}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",e),q.refresh()}function E(){m.innerHTML=""}function b(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}function L(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}const R=document.querySelector(".search-form"),$=document.querySelector(".load-more-btn");let d="",i=1;const w=15;R.addEventListener("submit",B);$.addEventListener("click",O);async function B(r){if(r.preventDefault(),d=r.currentTarget.elements.searchQuery.value.trim(),d===""){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}i=1,E(),u(),b();try{const e=await f(d,i);if(e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}y(e.hits),l();const s=Math.ceil(e.totalHits/w);i<s?L():a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){l(),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}}async function O(){i+=1,u(),b();try{const r=await f(d,i);y(r.hits),l(),H();const e=Math.ceil(r.totalHits/w);i>=e?(u(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(r){l(),a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"}),console.error(r)}}function H(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
